services:
    user_db:
        image: postgres:latest
        container_name: user-db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: user_db
        ports:
            - "5433:5432" # Exposing User DB on port 5432

    board_db:
        image: postgres:latest
        container_name: board-db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: board_db
        ports:
            - "5431:5432" # Exposing Board DB on port 5433

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com # Your pgAdmin login email
            PGADMIN_DEFAULT_PASSWORD: admin # Your pgAdmin login password
        ports:
            - "5050:80" # pgAdmin will be accessible on port 5050
        depends_on:
            - user_db
            - board_db
            - task_db
